export const bestiario = [
    {
        id: 1,
        nombre: "Alabarda de huesos",
        descripcion: "Esqueleto que empuña una naginata",
        imagen: "./assets/alabarda_de_hueso.png",
        tipo: "Enemigo común",
        drop: "Javalina, jamon y huevos",
        ubicacion: "Capilla Real",
        hp: 30,
        exp: 40
    },
    {
        id: 2,
        nombre: "Arca de huesos",
        descripcion: "Santuario portátil de calaveras transportado por sacerdotes esqueléticos.",
        imagen: "./assets/arca_de_huesos.png",
        tipo: "Enemigo elite",
        drop: "Frasco de monstruo 3, Escudo de calavera",
        ubicacion: "Catacumbas",
        hp: 250,
        exp: 40
    },
    {
        id: 3,
        nombre: "Bailarina fantasma",
        descripcion: "esqueleto con ataque en salto.",
        imagen: "./assets/bailarina_fantasma.png",
        tipo: "Enemigo común",
        drop: "Estrella de bufalo, mascara de piedra",
        ubicacion: "la guarida de Alamuerte",
        hp: 30,
        exp: 160
    },
    {
        id: 4,
        nombre: "Guardia alado",
        descripcion: "Guerrero esqueleto de vuelo lento.",
        imagen: "./assets/guardia_alado.png",
        tipo: "Enemigo común",
        drop: "Escudo de hierro, javalina",
        ubicacion: "Capilla Real",
        hp: 15,
        exp: 30
    },
    {
        id: 5,
        nombre: "Cabeza de pescado",
        descripcion: "Esqueleto con cabeza de pez que escupe fuego.",
        imagen: "./assets/cabeza_de_pescado.png",
        tipo: "Enemigo común",
        drop: "Resiste al hielo, Icebrand",
        ubicacion: "Cavernas Subterraneas",
        hp: 70,
        exp: 50
    },
    {
        id: 6,
        nombre: "Calavera de piedra",
        descripcion: "Calavera giratoria indestructible.",
        imagen: "./assets/calavera_de_piedra.png",
        tipo: "Enemigo elite",
        drop: "Ninguno",
        ubicacion: "Galeria de Marmol negro, Coliseo invertido, Muro exterior invertido",
        hp: "???",
        exp: "ninguno"
    },
    {
        id: 7,
        nombre: "Calavera fantasma",
        descripcion: "Cabeza de soldado ejecutado. Buscando venganza..",
        imagen: "./assets/calavera_fantasma.png",
        tipo: "Enemigo común",
        drop: "Sombrero de fieltro, resistente a la oscuridad",
        ubicacion: "Torre del Reloj",
        hp: 15,
        exp: 30
    },
    {
        id: 8,
        nombre: "Cimitarra de hueso",
        descripcion: "Esqueleto mercenario armado con una cimitarra.",
        imagen: "./assets/cimitarra_de_hueso.png",
        tipo: "Enemigo común",
        drop: "Espada corta, Oxido rojo",
        ubicacion: "Laboratorio de alquimia, Coliseo, Entrada",
        hp: 18,
        exp: 15
    },
    {
        id: 9,
        nombre: "Dhuron",
        descripcion: "Esqueleto sin cabeza, empuña un estoque.",
        imagen: "./assets/dhuron.png",
        tipo: "Enemigo elite",
        drop: "Coraza de cuero, estoque",
        ubicacion: "Biblioteca larga",
        hp: 32,
        exp: 50
    },
    {
        id: 10,
        nombre: "Esqueleto",
        descripcion: "Esqueleto animado magicamente",
        imagen: "./assets/esqueleto.png",
        tipo: "Enemigo común",
        drop: "Pocion de escudo, Frasco de monstruo 3",
        ubicacion: "Laboratorio de alquimia, Catacumbas Flotantes, Galeria de Marmol, Muro exterior",
        hp: 9,
        exp: 10
    },
    {
        id: 11,
        nombre: "Esqueleto arquero",
        descripcion: "Esqueleto equipado con arco.",
        imagen: "./assets/esqueleto_arquero.png",
        tipo: "Enemigo común",
        drop: "$400, Misil Magico",
        ubicacion: "Muro exterior, Cavernas Subterraneas",
        hp: 10,
        exp: 50
    },
    {
        id: 12,
        nombre: "Esqueleto de hombre pantera",
        descripcion: "Esqueleto de hombre pantera.",
        imagen: "./assets/esqueleto_de_hombre_pantera.png",
        tipo: "Enemigo elite",
        drop: "Pocion de Fuerza, Granate",
        ubicacion: "Catacumbas",
        hp: 33,
        exp: 50
    },
    {
        id: 13,
        nombre: "Esqueleto de sangre",
        descripcion: "Esqueleto revivido por la sangre que empapa sus huesos.",
        imagen: "./assets/esqueleto_de_sangre.png",
        tipo: "Enemigo elite",
        drop: "ninguno",
        ubicacion: "Laboratorio de Alquimia, Catacumbas, Catacumbas Flotantes",
        hp: 9,
        exp: "ninguna"
    },
    {
        id: 14,
        nombre: "Esqueleto de simio",
        descripcion: "Esqueleto de un simio que arroja barriles.",
        imagen: "./assets/esqueleto_de_simio.png",
        tipo: "Enemigo común",
        drop: "platano, TNT",
        ubicacion: "Muro Exterior, Cavernas subterraneas",
        hp: 10,
        exp: 20
    },
    {
        id: 15,
        nombre: "Hueso escupidor",
        descripcion: "Esqueleto de cuatro patas.Gotea veneno.",
        imagen: "./assets/hueso_escupidor.png",
        tipo: "Enemigo común",
        drop: "ninguno",
        ubicacion: "Laboratorio de Alquimia",
        hp: 18,
        exp: 20
    },
    {
        id: 16,
        nombre: "Jack O'Bones",
        descripcion: "Experto lanzador de armas.",
        imagen: "./assets/jackobones.gif",
        tipo: "Enemigo común",
        drop: "Shuriken, Estrella de fuego",
        ubicacion: "Galeria de marmol negro, Cavernas invertidas, Entrada invertida, Muro exterior invertido",
        hp: 20,
        exp: 150
    },
    {
        id: 17,
        nombre: "Lanzador",
        descripcion: "Esqueleto que arroja huesos.",
        imagen: "./assets/lanzador.png",
        tipo: "Enemigo común",
        drop: "Escudo de cuero, Escudo de caballero",
        ubicacion: "Galeria de Marmol",
        hp: 12,
        exp: 10
    },
    {
        id: 18,
        nombre: "Maestro de la espada",
        descripcion: "Maestro del combate con espadas gemelas.",
        imagen: "./assets/maestro_de_la_espada.png",
        tipo: "Enemigo elite",
        drop: "Shotel, Shuriken cruzado",
        ubicacion: "Coliseo",
        hp: 65,
        exp: 60
    },
    {
        id: 19,
        nombre: "Mosquetero",
        descripcion: "Esqueletos equipados con rifles.",
        imagen: "./assets/mosquetero.png",
        tipo: "Enemigo común",
        drop: "Misil Magico, Talisman",
        ubicacion: "Coliseo, Muralla exterior",
        hp: 24,
        exp: 20
    },
    {
        id: 20,
        nombre: "Nova Esqueleton",
        descripcion: "Esqueleto que dispara un poderoso haz de energia.",
        imagen: "./assets/nova_esqueleton.png",
        tipo: "Enemigo elite",
        drop: "Frasco de monstruo 3, Terminus Est",
        ubicacion: "",
        hp: 20,
        exp: 444
    },
    {
        id: 21,
        nombre: "Parantropo",
        descripcion: "Esqueleto gigante.",
        imagen: "./assets/parantropo.png",
        tipo: "Enemigo elite",
        drop: "Guantelete, Anillo de Varda",
        ubicacion: "Coliseo, Muro exterior inverso",
        hp: 100,
        exp: 50
    },
    {
        id: 22,
        nombre: "Pilar de huesos",
        descripcion: "Columna de calaveras de dinosaurio que escupen fuego.",
        imagen: "./assets/bonepillar.gif",
        tipo: "Enemigo elite",
        drop: "Antidoto, Mascara de Salon de baile",
        ubicacion: "Capilla Real",
        hp: 64,
        exp: 30
    },
    {
        id: 23,
        nombre: "Protector del mayal",
        descripcion: "Esqueleto equipado con un mayal de hierro con puas.",
        imagen: "./assets/flailguard.gif",
        tipo: "Enemigo elite",
        drop: "Morningstar, estofado de carne",
        ubicacion: "Torre del reloj",
        hp: 36,
        exp: 50
    },
    {
        id: 24,
        nombre: "Señor calavera",
        descripcion: "Espiritu calavera gigante.",
        imagen: "./assets/señor_calavera.png",
        tipo: "Enemigo elite",
        drop: "Cimitarra, Escudo de calavera",
        ubicacion: "Torre del reloj, Retorno",
        hp: 60,
        exp: 50
    },
    {
        id: 25,
        nombre: "Soldado de la espada",
        descripcion: "Novato en el combate de las espadas gemelas.",
        imagen: "./assets/soldado_de_la_espada.png",
        tipo: "Enemigo común",
        drop: "$400, Nakamura",
        ubicacion: "Coliseo",
        hp: 16,
        exp: 20
    },
    {
        id: 26,
        nombre: "Yorick",
        descripcion: "Esqueleto que persigue eternamente su propio craneo.",
        imagen: "./assets/yorick.gif",
        tipo: "Enemigo elite",
        drop: "Frasco de monstruo 3, Escudo de calavera",
        ubicacion: "Mantener al reves",
        hp: 10,
        exp: 300
    },
    {
        id: 27,
        nombre: "Zombi",
        descripcion: "Cadáveres frescos. Animados mágicamente.",
        imagen: "./assets/zombi.png",
        tipo: "Enemigo común",
        drop: "$100, Tunica de tela",
        ubicacion: "Entrada",
        hp: 1,
        exp: 5
    },
    {
        id: 28,
        nombre: "Zombi sangriento",
        descripcion: "Soldados de la Iglesia Oriental enviados hace 300 años.",
        imagen: "./assets/zombi_sangriento.png",
        tipo: "Enemigo elite",
        drop: "Tunica de Tela, Basilard",
        ubicacion: "Laboratorio de Alquimia, Entrada, Aposentos de Olrox",
        hp: 24,
        exp: 15
    },
    {
        id: 29,
        nombre: "Zombi volador",
        descripcion: "Zombis que atacan incluso cuando son cortados por la mitad.	.",
        imagen: "./assets/zombi_volador.png",
        tipo: "Enemigo común",
        drop: "Shuriken, Frankfurter",
        ubicacion: "La guarida de Alamuerte",
        hp: 190,
        exp: 50
    },
    {
        id: 30,
        nombre: "Arpía",
        descripcion: "Criatura con cabeza de mujer y cuerpo de pájaro..",
        imagen: "./assets/arpia.png",
        tipo: "Enemigo común",
        drop: "Manzana, Manzana de vida",
        ubicacion: "Torre del Reloj",
        hp: 26,
        exp: 70
    },
    {
        id: 31,
        nombre: "Búho",
        descripcion: "Búho de corral local. Mutado por la influencia del castillo.",
        imagen: "./assets/owl.gif",
        tipo: "Enemigo común",
        drop: "ninguno",
        ubicacion: "Coliseo, Entrada",
        hp: 26,
        exp: 30
    },
    {
        id: 32,
        nombre: "Caballero búho",
        descripcion: "Caballero fuertemente armado. Ataca con un búho entrenado.",
        imagen: "./assets/caballero_buho.png",
        tipo: "Enemigo elite",
        drop: "Sable, Medalla",
        ubicacion: "Coliseo, Entrada",
        hp: 160,
        exp: 50
    },
    {
        id: 33,
        nombre: "Cuervo negro",
        descripcion: "Cuervo carnívoro.",
        imagen: "./assets/blackcrow.gif",
        tipo: "Enemigo común",
        drop: "Aguamarina, Bollo de frijoles rojos",
        ubicacion: "Capilla Real",
        hp: 15,
        exp: 50
    },
    {
        id: 34,
        nombre: "Cuervo azul",
        descripcion: "Espíritu de un cuervo azul muerto hace mucho tiempo.",
        imagen: "./assets/blueraven.gif",
        tipo: "Enemigo común",
        drop: "Zircon, Bollo de cerdo",
        ubicacion: "Capilla Real",
        hp: 15,
        exp: 50
    },
    {
        id: 35,
        nombre: "Espantapájaros",
        descripcion: "Hombre empalado buscando un cerebro.",
        imagen: "./assets/espantapajaros.png",
        tipo: "Enemigo fantasma",
        drop: "Jabalina, Muramasa",
        ubicacion: "Biblioteca Prohibida",
        hp: 120,
        exp: 1000
    },
    {
        id: 36,
        nombre: "Cabeza de Medusa",
        descripcion: "Del cabello de Medusa.",
        imagen: "./assets/medusahead.gif",
        tipo: "Enemigo elite",
        drop: "Piedra resistente, Escudo de Medusa",
        ubicacion: "Galeria de Marmol Negro, Torre del Reloj,Guarida de Alamuerte, Muralla exterior, Torre del reloj invertida",
        hp: 12,
        exp: 20
    },
    {
        id: 37,
        nombre: "Cabeza de Medusa",
        descripcion: "Del cabello de Medusa. Puede petrificar.",
        imagen: "./assets/medusahead-2.gif",
        tipo: "Enemigo elite",
        drop: "Piedra resistente, Escudo de Medusa",
        ubicacion: "Galería de Mármol Negro, Torre del Reloj, Guarida del Alamuerte, Muralla Exterior, Torre del Reloj Invertida",
        hp: 12,
        exp: 30
    },
    {
        id: 38,
        nombre: "Hombre lobo (enemigo)",
        descripcion: "Mitad hombre, mitad lobo.",
        imagen: "./assets/hombre_lobo_(enemigo).png",
        tipo: "Enemigo elite",
        drop: "Puño de hierro, Yasutsuna",
        ubicacion: "Coliseo Inverso",
        hp: 280,
        exp: 200
    },
    {
        id: 39,
        nombre: "Huargo",
        descripcion: "Lobos que custodian la entrada del castillo.",
        imagen: "./assets/warg.gif",
        tipo: "Enemigo elite",
        drop: "ninguno",
        ubicacion: "Entrada",
        hp: 32,
        exp: 10
    },
    {
        id: 40,
        nombre: "Huargo de fuego",
        descripcion: "Lobo que escupe bolas de fuego.",
        imagen: "./assets/huargo_de_fuego.png",
        tipo: "Enemigo elite",
        drop: "Turquesa, Moneda Karma",
        ubicacion: "Cavernas Inversas",
        hp: 200,
        exp: 160
    },
    {
        id: 41,
        nombre: "Jinete de Huargo",
        descripcion: "Guerrero montado en un Huargo infernal.",
        imagen: "./assets/wargrider.gif",
        tipo: "Enemigo elite",
        drop: "ninguno",
        ubicacion: "Entrada Inversa",
        hp: 120,
        exp: 160
    },
    {
        id: 42,
        nombre: "Mosca amarga",
        descripcion: "Insecto mutado. Visible solo para magos.",
        imagen: "./assets/mosca_amarga.png",
        tipo: "Enemigo común",
        drop: "Pocion de la suerte, colgante mistico",
        ubicacion: "Laboratorio de nigromancia",
        hp: 4,
        exp: 120
    },
    {
        id: 43,
        nombre: "Murciélago",
        descripcion: "Murciélagos vampiro. Temidos como sirvientes del mal.",
        imagen: "./assets/murcielago.png",
        tipo: "Enemigo común",
        drop: "Pocion, Frasco de monstruo 2",
        ubicacion: "Cueva, Entrada, Catacumba Flotantes, Capilla Real, Cavernas Subterraneas",
        hp: 1,
        exp: 1
    },
    {
        id: 44,
        nombre: "Pantera negra",
        descripcion: "Criatura líquida. Adopta la forma de una pantera negra.",
        imagen: "./assets/pantera_negra.png",
        tipo: "Enemigo elite",
        drop: "Boleto de comida, Masamune",
        ubicacion: "Anticapilla",
        hp: 35,
        exp: 600
    },
    {
        id: 45,
        nombre: "Pez asesino",
        descripcion: "Maestro Cabeza de Pez.",
        imagen: "./assets/pez_asesino.png",
        tipo: "Enemigo común",
        drop: "Aquamarina, Sushi",
        ubicacion: "Cavernas Subterraneas",
        hp: 120,
        exp: 100
    },
    {
        id: 46,
        nombre: "Pulpo oscuro",
        descripcion: "Pulpo mutante malvado.",
        imagen: "./assets/pulpo_oscuro.png",
        tipo: "Enemigo elite",
        drop: "Sushi, te verde",
        ubicacion: "Cavernas Inversas",
        hp: 280,
        exp: 120
    },
    {
        id: 47,
        nombre: "Pájaro dodo",
        descripcion: "Ave rara. Huye al ver gente.",
        imagen: "./assets/pajaro_dodo.png",
        tipo: "Enemigo común",
        drop: "Broche de Corazon, Espada Runica",
        ubicacion: "Entrada Inversa",
        hp: 2,
        exp: 111
    },
    {
        id: 48,
        nombre: "Rana",
        descripcion: "Rana cavernícola.",
        imagen: "./assets/frog.gif",
        tipo: "Enemigo común",
        drop: "Puño Americano, Pizza",
        ubicacion: "Cavernas Subterraneas",
        hp: 2,
        exp: 20
    },
    {
        id: 49,
        nombre: "Sapo",
        descripcion: "Sapo agrandado mágicamente por un bautismo demoníaco.	",
        imagen: "./assets/toad.gif",
        tipo: "Enemigo común",
        drop: "Blue Knuckles, Pizza",
        ubicacion: "Cavernas Subterraneas",
        hp: 10,
        exp: 20
    },
    {
        id: 50,
        nombre: "Bestia de fuego infernal",
        descripcion: "Demonio que empuña el trueno. Conocido como Músico del Infierno.",
        imagen: "./assets/bestia_de_fuego_infernal.png",
        tipo: "Enemigo elite",
        drop: "Armadura relampago, Armadura de fuego",
        ubicacion: "Catacumbas",
        hp: 380,
        exp: 150
    },
    {
        id: 51,
        nombre: "Ctulhu",
        descripcion: "Demonio de fuego y hielo. Parece reacio a luchar.",
        imagen: "./assets/cthulhu.png",
        tipo: "Enemigo elite",
        drop: "Pentagrama, Pentagrama de Murcielago",
        ubicacion: "Guarida de Alamuerte, Galeria de Marmol, Laboratorio de nigromancia",
        hp: 200,
        exp: 100
    },
    {
        id: 52,
        nombre: "Demonio de fuego",
        descripcion: "demonio de fuego.",
        imagen: "./assets/demonio_de_fuego.png",
        tipo: "Enemigo elite",
        drop: "Escudo de Fuego, Marsil",
        ubicacion: "Laboratorio de nigromancia",
        hp: 320,
        exp: 666
    },
    {
        id: 53,
        nombre: "Demonio menor",
        descripcion: "Demonio de baja estatura que maneja magia. Invoca aliados demoníacos.",
        imagen: "./assets/lesserdemon.gif",
        tipo: "Enemigo común",
        drop: "Espada de obsidiana, Daga de Holbein",
        ubicacion: "Biblioteca larga, Laboratorio de nigromancia",
        hp: 400,
        exp: 100
    },
    {
        id: 54,
        nombre: "Diablillo",
        descripcion: "Pequeño demonio travieso.",
        imagen: "./assets/diablillo.png",
        tipo: "Enemigo común",
        drop: "Pocion de la suerte, Anillo de Feanor",
        ubicacion: "Torre del Reloj, Guarida de Alamuerte",
        hp: 43,
        exp: 66
    },
    {
        id: 55,
        nombre: "Gaibon",
        descripcion: "Demonio volador que escupe fuego.",
        imagen: "./assets/gaibon.gif",
        tipo: "Enemigo elite",
        drop: "ninguno",
        ubicacion: "Laboratorio de Alquimia, Cueva, Entrada",
        hp: 200,
        exp: 200
    },
    {
        id: 56,
        nombre: "Karasuman",
        descripcion: "Señor Demonio de los Cuervos.",
        imagen: "./assets/karasuman.gif",
        tipo: "Enemigo elite",
        drop: "Resistente a la oscuridad, Anillo de Feanor",
        ubicacion: "Torre del Reloj, Guarida de Alamuerte",
        hp: 500,
        exp: 1000
    },
    {
        id: 57,
        nombre: "Slogra",
        descripcion: "Demonio con lanza encantada.",
        imagen: "./assets/slogra.gif",
        tipo: "Enemigo elite",
        drop: "Ninguno",
        ubicacion: "Laboratorio de Alquimia, Cueva, Entrada",
        hp: 200,
        exp: 200
    },
    {
        id: 58,
        nombre: "Serpiente de Scylla",
        descripcion: "Serpiente que vive de Escila.",
        imagen: "./assets/scyllawyrm.gif",
        tipo: "Enemigo elite",
        drop: "Ninguno",
        ubicacion: "Cavernas Subterraneas",
        hp: 130,
        exp: 100
    },
    {
        id: 59,
        nombre: "Tritón I",
        descripcion: "Criatura legendaria. Ataca a todos los invasores.",
        imagen: "./assets/triton.png",
        tipo: "Enemigo elite",
        drop: "Zircon, Frasco monstruo 1",
        ubicacion: "Entrada",
        hp: 10,
        exp: 12
    },
    {
        id: 60,
        nombre: "Tritón II",
        descripcion: "Criatura legendaria. Ataca a todos los invasores. ",
        imagen: "./assets/merman.gif",
        tipo: "Enemigo elite",
        drop: "Zircon, Frasco monstruo 1",
        ubicacion: "Entrada",
        hp: 10,
        exp: 12
    },
    {
        id: 61,
        nombre: "Tritón marino",
        descripcion: "Tritón que escupe bolas de fuego. El más grande de su especie.",
        imagen: "./assets/merman-2.gif",
        tipo: "Enemigo elite",
        drop: "Zircon, Frasco monstruo 1",
        ubicacion: "Entrada",
        hp: 10,
        exp: 12
    },
    {
        id: 62,
        nombre: "Hierba cadáver",
        descripcion: "Planta con hojas afiladas como navajas.",
        imagen: "./assets/hierva_cadaver.png",
        tipo: "Enemigo común",
        drop: "Antidoto, Pocion",
        ubicacion: "Mina Abandonada, galeria de marmol negra, cueva, biblioteca larga",
        hp: 19,
        exp: 100
    },
    {
        id: 63,
        nombre: "Hierba de Venus",
        descripcion: "Regado con sangre humana.",
        imagen: "./assets/venus.png",
        tipo: "Enemigo elite",
        drop: "Diadema de coral, Refrescante para corazon",
        ubicacion: "Mina abandonada",
        hp: 100,
        exp: 150
    },
    {
        id: 64,
        nombre: "Hierba espinosa",
        descripcion: "Planta con hojas afiladas como navajas.",
        imagen: "./assets/hierva_espinosa.png",
        tipo: "Enemigo común",
        drop: "Uvas, fresas",
        ubicacion: "Mina abandonada, Galeria de marmol negro, Catacumbas, Biblioteca larga",
        hp: 12,
        exp: 20
    },
    {
        id: 65,
        nombre: "Hierba venus azul",
        descripcion: "Hierba Venus avanzada. Alimentada con sangre de demonio.",
        imagen: "./assets/bluevenusweed.gif",
        tipo: "Enemigo común",
        drop: "Zweihander, Refrescante para el corazon",
        ubicacion: "Cavernas inversa, Entrada inversa",
        hp: 100,
        exp: 1000
    },
    {
        id: 66,
        nombre: "Rosa de piedra",
        descripcion: "Planta mutada. Las semillas se petrifican.",
        imagen: "./assets/rosa_de_piedra.png",
        tipo: "Enemigo elite",
        drop: "Escudo de cuero, Vale de comida",
        ubicacion: "Galeria de marmol",
        hp: 60,
        exp: 60
    },
    {
        id: 67,
        nombre: "Armadura de hacha",
        descripcion: "Caballero hacha de bajo nivel.",
        imagen: "./assets/armadura_de_hacha.gif",
        tipo: "Enemigo elite",
        drop: "Hacha, Coraza de bronce",
        ubicacion: "Laboratorio de alquimia, Galeria de marmol",
        hp: 32,
        exp: 10
    },
    {
        id: 68,
        nombre: "Armadura de pulga",
        descripcion: "El hombre pulga armado con hacha y escudo.",
        imagen: "./assets/fleaarmor.gif",
        tipo: "Enemigo común",
        drop: "Pocion superior, Coraza de hierro",
        ubicacion: "Torre del reloj, Biblioteca larga",
        hp: 18,
        exp: 40
    },
    {
        id: 69,
        nombre: "Azaghal",
        descripcion: "Verdugo del Infierno.",
        imagen: "./assets/azaghal.png",
        tipo: "Enemigo elite",
        drop: "Piedra del pacto, Hoja del Luto",
        ubicacion: "Coliseo inverso",
        hp: 330,
        exp: 700
    },
    {
        id: 70,
        nombre: "Bruja de Salem",
        descripcion: "Brujas fantasmas de Salem.",
        imagen: "./assets/bruja_de_salem.png",
        tipo: "Enemigo elite",
        drop: "Diadema de oro, pastelito",
        ubicacion: "Mina abandonada, Laboratorio de nigromancia",
        hp: 180,
        exp: 80
    },
    {
        id: 71,
        nombre: "Caballero bomba",
        descripcion: "Caballero acorazado que lanza bombas.",
        imagen: "./assets/caballero_bomba.png",
        tipo: "Enemigo común",
        drop: "Tnt, Dinamita",
        ubicacion: "Torre del reloj inverso",
        hp: 46,
        exp: 140
    },
    {
        id: 72,
        nombre: "Caballero de hacha",
        descripcion: "Caballero con hacha bien armado.",
        imagen: "./assets/axeknight-2.gif",
        tipo: "Enemigo elite",
        drop: "Hacha, Escudo del señor del hacha",
        ubicacion: "Torreon del castillo, Coliseo, Muralla exterior",
        hp: 42,
        exp: 50
    },
    {
        id: 73,
        nombre: "Caballero de roca",
        descripcion: "Caballero acorazado que lanza piedras.",
        imagen: "./assets/caballero_de_roca.png",
        tipo: "Enemigo elite",
        drop: "Nudillos con joyas, Armadura de platino",
        ubicacion: "Cavernas inversas",
        hp: 160,
        exp: 250
    },
    {
        id: 74,
        nombre: "Caballero del Valhalla",
        descripcion: "Guerrero caido sediento de sangre.",
        imagen: "./assets/caballaero_del_valhalla.png",
        tipo: "Enemigo elite",
        drop: "Estoc, Claymore",
        ubicacion: "Coliseo, Aposentos de Olrox, Torre del reloj invertida",
        hp: 161,
        exp: 100
    },
    {
        id: 75,
        nombre: "Caballero encapuchado",
        descripcion: "Misterioso espadachín encapuchado.",
        imagen: "./assets/caballero_encapuchado.png",
        tipo: "Enemigo común",
        drop: "Flamberge, Espada celestial",
        ubicacion: "Torre del reloj, Torre del reloj inversa",
        hp: 65,
        exp: 80
    },
    {
        id: 76,
        nombre: "Chica cazadora",
        descripcion: "Espíritu de cazadora invisible.",
        imagen: "./assets/chica_cazadora.png",
        tipo: "Enemigo común",
        drop: "Were bane, Cheesecake",
        ubicacion: "Coliseo, Capilla Real",
        hp: 88,
        exp: 70
    },
    {
        id: 77,
        nombre: "Diplocéfalo",
        descripcion: "Una bestia de dos cabezas que da náuseas. ¿Cuál es la cabeza?",
        imagen: "./assets/diplocefalo.png",
        tipo: "Enemigo elite",
        drop: "Pentagrama, Tarta",
        ubicacion: "Galeria de marmol",
        hp: 80,
        exp: 50
    },
    {
        id: 78,
        nombre: "Duendecillo",
        descripcion: "Gremlin pirómano.",
        imagen: "./assets/duendecillo.png",
        tipo: "Enemigo común",
        drop: "Resistente al fuego, Armadura incendiaria",
        ubicacion: "Mina abandonada, Catacumbas, Laboratorio de nigromancia",
        hp: 100,
        exp: 60
    },
    {
        id: 79,
        nombre: "Gorgona",
        descripcion: "Bestia de guerra acorazada.",
        imagen: "./assets/gorgona.png",
        tipo: "Enemigo elite",
        drop: "Martillo, espada de piedra",
        ubicacion: "Galeria de marmol negro",
        hp: 240,
        exp: 555
    },
    {
        id: 80,
        nombre: "Guardián",
        descripcion: "Señor de la armadura de alto nivel.",
        imagen: "./assets/guardian.gif",
        tipo: "Enemigo elite",
        drop: "Gran espada, Vestimenta divina",
        ubicacion: "Galeria de marmol negro",
        hp: 500,
        exp: 1500
    },
    {
        id: 81,
        nombre: "Gurkha",
        descripcion: "Hermano gigante. Empuña un cuchillo gurkha.",
        imagen: "./assets/gurkha.gif",
        tipo: "Enemigo común",
        drop: "Cuchillo gigante, Chapado en oro",
        ubicacion: "Galeria de marmol, entrada",
        hp: 130,
        exp: 50
    },
    {
        id: 82,
        nombre: "Hombre de hojalata",
        descripcion: "Hombre de hojalata despiadado.",
        imagen: "./assets/hombre_de_hojalata.png",
        tipo: "Enemigo elite",
        drop: "Almuerzo A, Mojo mail",
        ubicacion: "Biblioteca Prohibida",
        hp: 48,
        exp: 1000
    },
    {
        id: 83,
        nombre: "Jinete pulga",
        descripcion: "El Hombre Pulga montado en un ganso de guerra especialmente entrenado.",
        imagen: "./assets/jinete_pulga.png",
        tipo: "Enemigo común",
        drop: "Pavo, Jamon y huevos",
        ubicacion: "Torreon del castillo",
        hp: 17,
        exp: 50
    },
    {
        id: 84,
        nombre: "Libro de hechizos",
        descripcion: "Libro de hechizos para principiantes.",
        imagen: "./assets/spellbook.gif",
        tipo: "Enemigo elite",
        drop: "$1000, pentagrama",
        ubicacion: "Biblioteca Larga",
        hp: 26,
        exp: 30
    },
    {
        id: 85,
        nombre: "Lossoth",
        descripcion: "Busca entre las tumbas y posee un amplio conocimiento.",
        imagen: "./assets/lossoth.png",
        tipo: "Enemigo elite",
        drop: "Solomillo, Firebrand",
        ubicacion: "Catacumbas",
        hp: 99,
        exp: 50
    },
    {
        id: 86,
        nombre: "Lápida sepulcral",
        descripcion: "Lápidas poseídas por espíritus malignos de los muertos..",
        imagen: "./assets/lapida_sepulcral.png",
        tipo: "Enemigo elite",
        drop: "Katana, te verde",
        ubicacion: "Mantener al reves",
        hp: 5,
        exp: 88
    },
    {
        id: 87,
        nombre: "Malaquías",
        descripcion: "Un demonio espantoso del infierno.",
        imagen: "./assets/malaquias.png",
        tipo: "Enemigo elite",
        drop: "Escudo oscuro, Armadura oscura",
        ubicacion: "La guarida de Alamuerte",
        hp: 450,
        exp: 666
    },
    {
        id: 88,
        nombre: "Marioneta",
        descripcion: "Marioneta demoníaca del infierno.",
        imagen: "./assets/marioneta.png",
        tipo: "Enemigo común",
        drop: "Pocion inteligente, diadema",
        ubicacion: "Galeria de marmol",
        hp: 20,
        exp: 30
    },
    {
        id: 89,
        nombre: "Martillo",
        descripcion: "Hermano gigante. Usa un enorme martillo de acero.",
        imagen: "./assets/martillo.png",
        tipo: "Enemigo elite",
        drop: "Martillo, chapado en oro",
        ubicacion: "Aposentos de Olrox",
        hp: 250,
        exp: 110
    },
    {
        id: 90,
        nombre: "Troll de las cavernas",
        descripcion: "Chupasangres preinteligente con lengua larga para succionar.",
        imagen: "./assets/troll_de_las_cavernas.png",
        tipo: "Enemigo elite",
        drop: "Bomba de Neutrones, Lapiz Lazuli",
        ubicacion: "Entrada inversa",
        hp: 88,
        exp: 333
    },
    {
        id: 91,
        nombre: "Minotauro (enemigo)",
        descripcion: "Mitad hombre, mitad toro.",
        imagen: "./assets/minotauro_(enemigo).png",
        tipo: "Enemigo elite",
        drop: "Solomillo, Armadura de furia",
        ubicacion: "Coliseo inverso",
        hp: 320,
        exp: 400
    },
    {
        id: 92,
        nombre: "Mitad congelado",
        descripcion: "Espíritu de hielo mestizo. Sirviente de Galamoth.",
        imagen: "./assets/mitad_congelado.png",
        tipo: "Enemigo elite",
        drop: "Collar de J, diadema de opalo",
        ubicacion: "Catacumbas flotantes",
        hp: 118,
        exp: 600
    },
    {
        id: 93,
        nombre: "Salomé",
        descripcion: "Joven bruja.",
        imagen: "./assets/salome.png",
        tipo: "Enemigo elite",
        drop: "Sombrero de mago, prisma de mana",
        ubicacion: "Catacumbas flotantes",
        hp: 210,
        exp: 450
    },
    {
        id: 94,
        nombre: "Sepulturero",
        descripcion: "Guardián de tumbas. Maestro del combate sin armas.",
        imagen: "./assets/sepulturero.png",
        tipo: "Enemigo común",
        drop: "Sopa de miso, Natou",
        ubicacion: "Catacumbas, Coliseo",
        hp: 123,
        exp: 60
    },
    {
        id: 95,
        nombre: "Señor de la armadura",
        descripcion: "Guerrero no muerto fuertemente acorazado.",
        imagen: "./assets/armorlord.gif",
        tipo: "Enemigo elite",
        drop: "Estoque, Sable",
        ubicacion: "Coliseo, Muralla exterior",
        hp: 84,
        exp: 100
    },
    {
        id: 96,
        nombre: "Señor de la espada",
        descripcion: "Caballero armado con una gran espada.	",
        imagen: "./assets/señor_de_la_espada.png",
        tipo: "Enemigo elite",
        drop: "Cutlass, Bekatowa",
        ubicacion: "Torre del reloj, Muralla exterior",
        hp: 61,
        exp: 60
    },
    {
        id: 97,
        nombre: "Señor de los platos",
        descripcion: "Caballero fuertemente armado con una bola de hierro.",
        imagen: "./assets/señor_de_los_platos.png",
        tipo: "Enemigo elite",
        drop: "Bola de hierro, bomba de neutrones",
        ubicacion: "Coliseo, Galeria de marmol",
        hp: 90,
        exp: 90
    },
    {
        id: 98,
        nombre: "Tomo mágico",
        descripcion: "Libro de armas antiguas.",
        imagen: "./assets/magictome.gif",
        tipo: "Enemigo elite",
        drop: "$2000, Saber",
        ubicacion: "Biblioteca larga",
        hp: 22,
        exp: 35
    },
    {
        id: 99,
        nombre: "Cápsula de globo",
        descripcion: "Contiene innumerables semillas venenosas.",
        imagen: "./assets/capsula_de_globo.png",
        tipo: "Enemigo común",
        drop: "ninguno",
        ubicacion: "Anti-Capilla, Cavernas inversas",
        hp: 3,
        exp: 88
    },
    {
        id: 100,
        nombre: "Espada espectral (lvl 36)",
        descripcion: "Espada demoníaca maligna. Provoca fenómenos poltergeist.",
        imagen: "./assets/spectralsword-3.gif",
        tipo: "Enemigo elite",
        drop: "Gurthang, Espada de Mablung",
        ubicacion: "Anti-capilla",
        hp: 540,
        exp: 440
    },
    {
        id: 101,
        nombre: "Espada espectral (nivel 13)",
        descripcion: "Espada demoníaca maligna. Provoca fenómenos poltergeist.",
        imagen: "./assets/spectralsword-2.gif",
        tipo: "Enemigo elite",
        drop: "Espada ancha, Espada bastarda",
        ubicacion: "Los aposentos de Olrox",
        hp: 90,
        exp: 80
    },
    {
        id: 102,
        nombre: "Espada vandala",
        descripcion: "El Señor de la Espada empuña  su espada incluso cuando está desterrado.",
        imagen: "./assets/espada_vandala.png",
        tipo: "Enemigo elite",
        drop: "Espada sagrada, Muramasa",
        ubicacion: "Torre del reloj",
        hp: 120,
        exp: 100
    },
    {
        id: 103,
        nombre: "Cuchilla",
        descripcion: "Hermano mayor de los gigantes. Empuña dos enormes dagas..",
        imagen: "./assets/blade.gif",
        tipo: "Enemigo elite",
        drop: "Espada de cazador, Chapada en oro",
        ubicacion: "Galeria de marmol negra, Entrada, Aposentos de Olrox",
        hp: 380,
        exp: 100
    },
    {
        id: 104,
        nombre: "Guardia de lanza",
        descripcion: "Guerrero con armadura y naginata.",
        imagen: "./assets/guardia_de_lanza.png",
        tipo: "Enemigo común",
        drop: "Javalina, Coraza de hierro",
        ubicacion: "Muro exterior, Cavernas subterraneas",
        hp: 20,
        exp: 70
    },
    {
        id: 105,
        nombre: "Mesa ouija",
        descripcion: "Mesa de Ouija poseída.",
        imagen: "./assets/mesa_ouija.png",
        tipo: "Enemigo elite",
        drop: "Te de cebada, jugo matutino",
        ubicacion: "Galeria de marmol",
        hp: 20,
        exp: 20
    },
    {
        id: 106,
        nombre: "Señor del disco",
        descripcion: "Caballero acorazado que empuña un disco.",
        imagen: "./assets/señor_del_disco.png",
        tipo: "Enemigo elite",
        drop: "Chakram, espada de joyas",
        ubicacion: "Catacumbas",
        hp: 450,
        exp: 140
    },
    {
        id: 107,
        nombre: "Hombre de barro",
        descripcion: "Golem de barro animado.",
        imagen: "./assets/hombre_de_barro.png",
        tipo: "Enemigo elite",
        drop: "ninguno",
        ubicacion: "Biblioteca larga",
        hp: 15,
        exp: 50
    },
    {
        id: 108,
        nombre: "Lodo vivo",
        descripcion: "Monstruo hecho de gel.",
        imagen: "./assets/slime.gif",
        tipo: "Enemigo común",
        drop: "ninguno",
        ubicacion: "Catacumbas",
        hp: 32,
        exp: 50
    },
    {
        id: 109,
        nombre: "Schmoo",
        descripcion: "Monstruo apodado Schmoo",
        imagen: "./assets/schmoo.png",
        tipo: "Enemigo común",
        drop: "Ramen, Crissaegrim",
        ubicacion: "Biblioteca Prohibida",
        hp: 50,
        exp: 1000
    },
    {
        id: 110,
        nombre: "Slime grande",
        descripcion: "Monstruo creado a partir de una sustancia gelatinosa viscosa.",
        imagen: "./assets/slime_grande.png",
        tipo: "Enemigo común",
        drop: "Ninguno",
        ubicacion: "Catacumbas",
        hp: 64,
        exp: 100
    },
    {
        id: 111,
        nombre: "Ectoplasma",
        descripcion: "Manifestaciones físicas de almas atormentadas sin cuerpo..",
        imagen: "./assets/ectoplasm.gif",
        tipo: "Enemigo fantasma",
        drop: "Desmaldicion, Prisma de mana",
        ubicacion: "Biblioteca larga",
        hp: 18,
        exp: 70
    }
];